# Generated by Django 4.1.8 on 2023-04-23 12:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('blog', '0002_categoria_rename_homepage_articulospage_articulopage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['name'], 'verbose_name': 'Categorias', 'verbose_name_plural': 'Categorias del Blog'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, help_text='Un tag para identificar articulos', max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='articulopage',
            name='categorias',
        ),
        migrations.AlterField(
            model_name='articulopage',
            name='contenido',
            field=wagtail.fields.RichTextField(blank=True, help_text='contenido del articulo'),
        ),
        migrations.AlterField(
            model_name='articulopage',
            name='imagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portada', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='articulopage',
            name='categorias',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.categoria'),
        ),
    ]
