# Generated by Django 4.1.8 on 2023-04-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('blog', '0003_articulolistingpage_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticuloListingPage',
            new_name='ArticulosListingPage',
        ),
    ]
