# Generated by Django 4.1.8 on 2023-04-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_articulopage_categorias_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticulosListingPage',
        ),
    ]
